version: '3.1'
services:

  stats-server:
    build: statistics/stat-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=s

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=s

  ewm-service:
    build: main-service/
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=s

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=s