CREATE TABLE IF NOT EXISTS events (
    id INT64 GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    app VARCHAR(50) NOT NULL,
    uri VARCHAR(50) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);